name: Upload Appium Test Report

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  upload-report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upload Test Reports Excel
      uses: actions/upload-artifact@v3
      with:
        name: Automated-Test-Reports
        path: |
          e2e-tests/E2E_Test_Report.xlsx
          e2e-tests/Vulnerability_Test_Report.xlsx
