name: Upload Appium Test Report

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  upload-report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upload Appium Test Report
      uses: actions/upload-artifact@v3
      with:
        name: appium-test-reports
        path: e2e-tests/Appium_Test_Report.xlsx

    - name: Upload Vulnerability Test Report
      uses: actions/upload-artifact@v3
      with:
        name: vulnerability-reports
        path: e2e-tests/Vulnerability_Test_Report.xlsx
